<?php
  $academic_subjects_obj = new academic_subjects;
  // var_export($_POST);
  switch ($_POST['what_to_do']) {
    case 'new':
      $academic_subjects_obj->add_academic_subject();
      break;
    case 'update':
      $academic_subjects_obj->update_academic_subject();
      break;
    case 'delete':
      $academic_subjects_obj->delete_academic_subject();
      break;
    case 'count':
      return $academic_subjects_obj->total();
      break;

    case 'get_full_data':
      return $academic_subjects_obj->get_academic_subjects();
      break;

    default:
      // code...
      break;
  }





?>
