<?php
  get_header("Academic Subjects ");
  $academic_subjects_obj = new academic_subjects;

  $user_info_obj = new user_info;
?>



 <!-- START DEFAULT DATATABLE -->
 <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Academic Subjects</h3>
      <ul class="panel-controls">
        <li><a href="#" class="panel-collapse"><span class="fa fa-angle-down"></span></a></li>
        <li><a href="#" class="panel-refresh"><span class="fa fa-refresh"></span></a></li>
        <li><a href="#" class="panel-remove"><span class="fa fa-times"></span></a></li>
      </ul>
      <button class="btn btn-success new_subject pull-right" ><i class="fa fa-plus"></i> Subject</button>
      <?php data_exporter("academic-subjects") ?>
    </div>
    <div class="panel-body">
        <table class="table datatable" id="academic-subjects">
            <thead>
                <tr>
                    <th>Subject Name</th>
                    <th>Subject Description</th>
                    <?php if(in_array('can_edit_academic_subject',$_SESSION['user_session_role_capabilities'])): ?>
                    <th>Edit</th>
                      <?php endif; ?>
                      <?php if(in_array('can_delete_academic_subject',$_SESSION['user_session_role_capabilities'])): ?>
                    <th>Delete</th>
                  <?php endif; ?>


                </tr>
            </thead>
            <tbody>
                <?php
                    $subjects = $academic_subjects_obj->get_academic_subjects();
                    foreach ($subjects as $key => $v):
                ?>
                <tr>
                    <td><?php echo $v['name'] ?></td>
                    <td><?php echo $v['description']?></td>
                    <?php if(in_array('can_edit_academic_subject',$_SESSION['user_session_role_capabilities'])): ?>
                    <td>
                        <a href="javascript://"  data-name="<?php echo $v['name']?>" data-descriptione="<?php echo $v['description']?>" data-token="<?php echo $v['token']?>"   class="btn btn-success edit_subject"><i class="glyphicon glyphicon-edit"></i></a>
                    </td>
                    <?php endif; ?>
                    <?php if(in_array('can_delete_academic_subject',$_SESSION['user_session_role_capabilities'])): ?>
                    <td>
                        <a href="javascript://" data-name="<?php echo $v['name']?>"  data-token="<?php echo $v['token']?>" class="btn btn-danger delete_subject"><i class="glyphicon glyphicon-trash"></i></a>
                    </td>
                    <?php endif; ?>
                </tr>
              <?php endforeach;?>

            </tbody>
        </table>
    </div>
</div>
<!-- END DEFAULT DATATABLE -->
<script type="text/javascript">

  function academic_subject(){
    this.update = function()
                  {
                    $(".edit_subject").click(function(){
                      var name = $(this).attr("data-name");
                      var description = $(this).attr("data-descriptione");
                      var token = $(this).attr("data-token");
                      var modalTitle =  "<strong>" + "Editing " + name + "</strong>" ;
                      var template = '<form class="" id="form_subject" action="javascript://" method="post">'
                      + '<div class="form-group">'
                      + '<label for="">Subject Name</label>'
                      + '<input type="text" id="name" name="name" value="" class="form-control" required>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<label for="">Subject Token</label>'
                      + '<input type="text" id="token" name="token" value="" class="form-control" readonly>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<label for="">Subject Description</label>'
                      + '<textarea name="description" id="description" class="form-control" rows="2"></textarea>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<button type="submit" name="" id="modalSubmitButton" class="btn btn-success"><i class="fa fa-save"></i> Save </button>'
                      + '</div>'
                      + '</form>'
                      $("#modalTitle").html( modalTitle );
                      // alert( name + description + token );
                      $("#thisModal").modal("show");
                      $("#thisModalBody").html(template);
                      $("#name").val(name);
                      $("#description").val( description);
                      $("#token").val(token);
                      $("#form_subject").submit(function(){
                        var data = $(this).serialize();

                        $.ajax({
                          method : "POST",
                          url : location.href + "/crud",
                          data: data + "&what_to_do=update",
                          cache : false,
                          beforeSend : function(){
                            notify.ajax_beforeSend();

                          },
                          complete: function(){

                          },
                          success: function(data){
                            notify.ajax_beforeComplete();
                            notify.noty(data);
                            // alert(data);
                          }
                        })
                      })


                    });
                  };
    this.delete = function(){
      $(".delete_subject").click(function(){

        var name = $(this).attr("data-name");
        var token = $(this).attr("data-token");
        var confirm = subject.confirm( "Are you you want to delete this subject " + name);
        // alert(confirm);
        if( confirm == false ){
          return false;
        }
        var data = "token=" + token;
        $.ajax({
          method : "POST",
          url : location.href + "/crud",
          data: data + "&what_to_do=delete",
          cache : false,
          beforeSend : function(){
            notify.ajax_beforeSend();
          },
          complete: function(){

          },
          success: function(data){
            notify.ajax_beforeComplete();
            notify.noty(data);
          }
        });

      })
    },
    this.create = function()
                  {
                    $(".new_subject").click(function(){
                      var modalTitle =  "<strong> NEW SUBJECT</strong>" ;
                      var template = '<form class="" id="form_new_subject" action="javascript://" method="post">'
                      + '<div class="form-group">'
                      + '<label for="">Subject Name</label>'
                      + '<input type="text" id="name" name="name" value="" class="form-control" required>'
                      + '</div>'

                      + '<div class="form-group">'
                      + '<label for="">Subject Description</label>'
                      + '<textarea name="description" id="description" class="form-control" rows="2"></textarea>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<button type="submit" name="" id="modalSubmitButton" class="btn btn-success"><i class="fa fa-save"></i> Save </button>'
                      + '</div>'
                      + '</form>'
                      $("#modalTitle").html( modalTitle );
                      $("#thisModal").modal("show");
                      $("#thisModalBody").html(template);

                      $("#form_new_subject").submit(function(){
                        var data = $(this).serialize();
                        // alert(location.href + "/crud");

                        $.ajax({
                          method : "POST",
                          url : location.href + "/crud",
                          data: data + "&what_to_do=new",
                          cache : false,
                          beforeSend : function(){
                            notify.ajax_beforeSend();

                          },
                          complete: function(){

                          },
                          success: function(data){
                            form.emptyform("#form_new_subject");
                            notify.ajax_beforeComplete();
                            notify.noty(data);
                            // alert(data);
                          }
                        })
                      })


                    });
                  };
    this.confirm = function ($msg){
      return confirm($msg);
    }

  }
 var subject = new academic_subject;
 subject.update();
 subject.delete();
 subject.create();
</script>

<!-- Modal content-->
<div class="modal  fade-in" id="thisModal" role="dialog">
  <div class="modal-dialog  modal-md">
    <div class="modal-content ">

      <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="modalTitle" ></h4>
      </div>

      <div class="modal-body" id="thisModalBody">
      </div>

      <div class="modal-footer ">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<?php get_footer()?>
