<div class="btn-group">
  <a href="<?php echo APP_PATH?>leave/new" class="btn btn-info"><i class="fa fa-plus"></i> New </a>
  <a href="javascript://" class="btn btn-primary" onclick="print()"><i class="fa fa-print"></i>  Print</a>
  <a href="?no-distraction" class="btn btn-warning" ><i class="fa fa-eye"></i>  Screen View</a>
</div>
<?php
  $liv_obj = new leave;
  $results = $liv_obj->full_data();
   unset($results['row_count']);
  // var_dump($results);
?>
<table class="table table-striped table-bordered table-hover" id="datatable" cellspacing="0" width="100%" >
  <thead>
    <tr>
      <th>ID</th>
      <th>Annex</th>
      <th>Date</th>
      <th>Year</th>
      <th>Term</th>
      <th>Staff</th>
      <th>No. Days</th>
      <th>Desired Dates</th>
      <th>Purpose</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody><?php
    $liv_obj = new leave;
    $results = $liv_obj->full_data();
    if($results !== false)
    foreach($results as $result):
      $d_days =  unserialize($result['desired_days']);
      $purposes =  unserialize($result['purpose']);
  ?>
    <tr>
      <td><?php echo $result['id'];  ?></td>
      <td><?php echo $result['annex'];  ?></td>
      <td><?php echo $result['date'];  ?></td>
      <td><?php echo $result['year'];  ?></td>
      <td><?php echo $result['term'];  ?></td>
      <td><?php echo get_user_full_name( array( 'id' => $result['staff'] ) );  ?></td>
      <td></td>
      <td >
        <ul>
        <?php
          foreach($d_days as $day):
            echo "<li>{$day}</li></br>";
          endforeach;
        ?>
        </ul>

      </td>
      <td >
        <ul>

        <?php
            foreach($purposes as $purpose):
              echo "<li>{$purpose}</li></br>";
            endforeach;
        ?>
        </ul>
      </td>
      <td>
          <a href="<?php echo APP_PATH."leave/view?token={$result['token']}" ?>" class="btn btn-warning"> View</a>
      </td>

    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
