<?php
	get_header( "CBT Engine" );
	$db_obj = new Database;
	$connect = $db_obj->dbConnection();
 ?>

<style>
.style1 {
	color: #FFFFFF;
	font-weight: bold;
}
.style2 {
	color: #990000;
	font-weight: bold;
}
.style4 {
	color: #000000;
	font-weight: bold;
}
.style5 {color: #990033}
.style6 {color: #ECE9D8}
.style7 {
	color: #993300;
	font-weight: bold;
}
.style8 {
	color: #6633CC;
	font-weight: bold;
}

.errors {

	color: #FF0000;
	font-weight: bold;
}
.tot {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 16px;
	color: #000000;
}
.tot {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color: #000000;

}
.tans {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color:#00CC66 ;
}
.fans {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color:#FF0000 ;
}
</style>

<?php
	 if( in_array( strtolower( $_SESSION['user_session']->user_role ) , array('admin' , 'teacher' , 'student' ) ) ):/*This is user access
	 control open to ADMIN, STUDENTS,SUPER ADMIN AND TEACHERS*/
?>

<?php
	$_GET  = filter_input_array(INPUT_GET, FILTER_SANITIZE_STRING);
	$_POST = filter_input_array(INPUT_POST, FILTER_SANITIZE_STRING);
	$action = $_GET['action'];//this get the admin action
	$today = date("F j, Y, g:i a");
	echo $today;


	switch ($action) {
		case 'option':
			include __DIR__ . DS . "stepper" . DS . "option.phtml";
			break;

		case 'listSubjects':
			include __DIR__ . DS . "stepper" . DS . "subjects.phtml";
			break;

		case 'getSubjectid':
			// code...
			break;
		case 'viewResulthistory':
			include __DIR__ . DS . "stepper" . DS . "results.phtml";
			break;

		default:
			include __DIR__ . DS . "stepper" . DS . "option.phtml";
			break;
	}

?>


<?php
	$action = $_GET['action'];
	if($action =='getSubjectid'):
	?>
	<div class="col-md-12">
	<div class="box box-danger">
	<div class="box-header bg-aqua" >
	<h2 class="box-title"><span class="badge bg-red"><strong><i class="fa fa-questionmark fa-fw"></i> <?php
		echo get_setting('site_name'); ?> TEST AREA</strong> </span></h2><p>
	</div>
	<div class="box-body" >

		<div class="col-md-12 jumbotron" style="text-align:center;">
			<h2>SUBJECT: <strong><?php echo strtoupper($_GET['subname']);
			$subname = $_GET['subname'];
			?></strong></h2>

			<?php
			$subid = $_GET['subid'];
			$rs1=mysqli_query( $connect, " SELECT * FROM academic_subjects WHERE id='$subid' " );
			$row1 = mysqli_fetch_array( $rs1 );
			echo "<h1 align=center><font color=blue> $row1[1]</font></h1>";
			$rs = mysqli_query( $connect , " SELECT * FROM skulpro_test WHERE subject_id='$subid' " );

			if( mysqli_num_rows( $rs ) < 1 ):

				echo '<div class="alert alert-warning">
				<button class="close" data-dismiss="alert">&times; </button><i class="fa fa-question-mark"></i>Sorry! No test associated with this subject  is already in the suject list .</div>';

			else:
			?>
				<table id="viewNote" class="table table-striped table-bordered table-hover" 	cellspacing="0" width="100%">
					<thead>
						<tr>
							<th> Test name</th>
							<th> Total Question</th>
							<th> Year</th>
							<th> Duration</th>
							<th> Action</th>
						</tr>
					</thead>

					<tbody>
						<?php
							echo "<h2 class=head1> Select Quiz Name to Give Quiz </h2>";
							while( $row = mysqli_fetch_object( $rs ) ):
						?>
						<tr>

							<td>
								<a href="?testRoom&action=takeTest&testid=<?php echo $row->id?>&
								subid=<?php echo $subid;?>&subname=<?php echo $subname ;
								?>"><font size=5> <?php echo $row->test_name;?></font></a>
							</td>

							<td> <a href="#"> <?php echo $row->total_question?></a> </td>

							<td> <a href="#"> <?php echo $row->year?></a> </td>

							<td> <a href="#"> <?php echo $row->duration?></a> </td>

							<td>
								<a href="?testRoom&action=takeTest&testid=<?php echo $row->id?>&
								subid=<?php echo $subid?>&subname=<?php echo $subname ;
								?>" class="btn btn-success">
								<i class="fa fa-clock"></i> START TEST</a>
							</td>
						</tr>
					<?php
						endwhile;
					endif;
					?>
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer bg-aqua"> </div>


	</div>
</div>
<?php
endif;//getsubjectlist
?>


<?php
	$action = $_GET['action'];
	if($action =='takeTest'):
	?>
<?php
@extract($_POST);
$testid = $_GET['testid'];
$subid = $_GET['subid'];
@extract($_SESSION);
/*$rs=mysql_query("select * from skulpro_question where test_id=$tid",$cn) or die(mysql_error());
if($_SESSION[qn]>mysql_num_rows($rs))
{
unset($_SESSION[qn]);
exit;
}*/
?>
<div class="col-md-12">
	<div class="box box-danger">
	<div class="box-header bg-aqua" >
	<h2 class="box-title"><strong><i class="fa fa-questionmark fa-fw"></i> <?php
		echo get_setting('site_name'); ?> TEST AREA</strong> </h2><p>
	</div>
	<div class="box-body" >

<div class="col-md-12 jumbotron" style="text-align:center;">
<h1> TEST: <strong><?php echo strtoupper($_GET['subname']);
$subname = $_GET['subname'];
?></strong> </h1>

<?php
/*$rs=mysql_query("select * from skulpro_question where test_id=$tid",$cn) or die(mysql_error());
if($_SESSION[qn]>mysql_num_rows($rs))
{
unset($_SESSION[qn]);
exit;
}*/
if(isset($subid) && isset($testid))
{
$_SESSION['sid']=$subid;
$_SESSION['tid']=$testid;
}
/*if(!isset($_SESSION[sid]) || !isset($_SESSION[tid]))
{
	header("location: index.php");
}*/
?>
<?php
@extract($_POST);
$testid = $_GET['testid'];
$subid = $_GET['subid'];
@extract($_SESSION);

$query="SELECT * FROM skulpro_question";

$rs=mysqli_query( $connect , " SELECT * FROM skulpro_test_questions WHERE test_id = $tid ") or die( mysqli_error() );
if(!isset( $_SESSION['qn'] ) )
{
	$_SESSION['qn'] = 0;
	mysqli_query( $connect, "DELETE FROM skulpro_useranswer WHERE sess_id=' ". session_id() ." ' " ) or die(mysqli_error());
	$_SESSION['trueans'] = 0;

}
else
{
		if( isset($submit) && $submit=='Next Question' && isset($ans))
		{
				mysqli_data_seek($rs,$_SESSION['qn']);
				$row= mysqli_fetch_row($rs);
				mysqli_query($connect, "insert into skulpro_useranswer(sess_id, test_id, que_des, ans1,ans2,ans3,ans4,true_ans,your_ans) values ('".session_id()."', $tid,'$row[2]','$row[3]','$row[4]','$row[5]', '$row[6]','$row[7]','$ans')") or die(mysql_error());
				if($ans==$row[7])
				{
							$_SESSION['trueans']=$_SESSION['trueans']+1;
				}
				$_SESSION['qn']=$_SESSION['qn']+1;
		}
		else if( isset($submit) && $submit =='Get Result' && isset($ans))
		{
				mysqli_data_seek($rs,$_SESSION['qn']);
				$row= mysqli_fetch_row($rs);
				mysqli_query($connect, "insert into skulpro_useranswer(sess_id, test_id,
				que_des, ans1,ans2,ans3,ans4,true_ans,your_ans)
				values ('".session_id()."', $tid,'$row[2]','$row[3]','$row[4]','$row[5]',
				'$row[6]','$row[7]','$ans')") or die(mysqli_error());
				if($ans==$row[7])
				{
							$_SESSION[trueans]=$_SESSION[trueans]+1;
				}
				echo "<h1 class=head1> Result</h1>";
				$_SESSION[qn]=$_SESSION[qn]+1;
				echo "<Table align=center><tr class=tot><td>Total Question<td> $_SESSION[qn]";
				echo "<tr class=tans><td>True Answer<td>".$_SESSION[trueans];
				$w=$_SESSION[qn]-$_SESSION[trueans];
				echo "<tr class=fans><td>Wrong Answer<td> ". $w;
				echo "</table>";
				$user = $urow['userName'];
				mysqli_query($connect, "insert into skulpro_result(login,test_id,test_date,score)
				values('$user','$tid','$today',$_SESSION[trueans])");
				echo '<h1 align="center"><a href="?testRoom&action=viewResult"> Review Question</a> </h1>';
				unset( $_SESSION['qn'] );
				unset( $_SESSION['sid'] );
				unset( $_SESSION['tid'] );
				unset( $_SESSION['trueans'] );
				exit;
		}
}
$rs = mysqli_query( $connect, "SELECT * FROM skulpro_test_questions WHERE test_id={$tid} " ) or die(mysqli_error());
if( $_SESSION['qn'] > mysqli_num_rows( $rs ) -1 ):
	unset($_SESSION['qn']);
	echo "<h1 class='text-danger'>Some Error  Occured. Please start again</h1>";
	//session_destroy();
	echo ' <a href="?testRoom&action=listSubjects" class="btn btn-info"> <i class="fa fa-clock"></i>Please Start Again</a>';
	exit;
endif;
mysqli_data_seek($rs,$_SESSION[qn]);
$row= mysqli_fetch_row($rs);
$rowCount = mysqli_num_rows($rs);
?>
<?php
if($rowCount > 0):
echo "<form name=myfm method=post action=>";
echo "<table width=100%> <tr> <td width=30>&nbsp;<td> <table border=0>";
$n=$_SESSION[qn]+1;
echo "<tR><td align=left><span class=style2><h2>Que ".  $n .": $row[2]</h2></style>";
echo "<tr><td align=left
class=style8><h4>A: &nbsp; &nbsp;  <input type=radio name=ans value=1> $row[3]</h4>";
echo "<tr><td align=left
class=style8><h4>B: &nbsp; &nbsp;  <input type=radio name=ans value=2> $row[4]</h4>";
echo "<tr><td align=left
class=style8><h4>C: &nbsp; &nbsp;  <input type=radio name=ans value=3> $row[5]</h4>";
echo "<tr><td align=left
class=style8><h4>D: &nbsp; &nbsp;  <input type=radio name=ans value=4> $row[6]</h4>";
endif;
?>
<?php
if($_SESSION[qn]<mysqli_num_rows($rs)-1)
echo '<tr><td><input type="submit" class="btn btn-success" name="submit" value="Next Question"></form>';
else
echo '<tr><td><input type="submit" class="btn btn-info" name="submit" value="Get Result"></form>';
echo "</table></table>";
?>

</div>
</div>

<div class="box-footer bg-aqua">
 </div>


</div>
</div>
<?php
endif;
?>

<?php
//This views the test result
	$action = $_GET['action'];
	if($action =='viewResult'):
	?>
<div class="col-md-12">
	<div class="box box-danger">
	<div class="box-header bg-aqua" >
	<h2 class="box-title"><strong><i class="fa fa-questionmark fa-fw"></i> <?php
		echo get_setting('site_name'); ?> TEST AREA</strong> </h2><p>
	</div>
	<div class="box-body" >

<div class="col-md-12 jumbotron" style="text-align:center;">
<h1 class="head1"> Review Test Question</h1>
<p>
<div class="well"> This <i>Test review</i> will take your get the correct answers of the questions you missed. The correct answer is colored in green.</div>
<?php
	@extract($_POST);
$testid = $_GET['testid'];
$subid = $_GET['subid'];
@extract($_SESSION);

if(!isset($_SESSION[qn]))
{
		$_SESSION[qn]=0;
}
else if($submit=='Next Question' )
{
	$_SESSION[qn]=$_SESSION[qn]+1;

}

$rs=mysqli_query($connect, "SELECT * from skulpro_useranswer WHERE sess_id='" . session_id() ."'");
mysqli_data_seek($rs,$_SESSION[qn]);
$row= mysqli_fetch_row($rs);
echo '<form name="myfm" method="post" action="">';
echo "<table width=100%> <tr> <td width=30>&nbsp;<td> <table border=0>";
$n=$_SESSION[qn]+1;
echo "<tR><td align=left><span class=style2><h2>Que ".  $n .": $row[2]</h2></style>";
echo "<tr><td align=left class=".($row[7]==1?'tans':'style8')."><h4>A: $row[3]</h4>";
echo "<tr><td align=left class=".($row[7]==2?'tans':'style8')."><h4>B: $row[4]</h4>";
echo "<tr><td align=left class=".($row[7]==3?'tans':'style8')."><h4>C: $row[5]</h4>";
echo "<tr><td align=left class=".($row[7]==4?'tans':'style8')."><h4>D: $row[6]</h4>";
if($_SESSION[qn] < mysqli_num_rows($rs)-1)
{
echo '<tr><td><input class="btn btn-info" type="submit" name="submit" value="Next Question"></form>';
}

else
{
echo '<tr><td><a href="?testRoom&action=listSubjects"  class="btn btn-info btn-lg">Finish</a></form>';
echo '</table></table>';
}
?>
</div>
</div>

<div class="box-footer bg-aqua">
 </div>


</div>
</div>
<?php
endif;

?>




<?php
endif;//This is user access control closed
get_footer();

?>
