<div class="col-md-12">
  <div class="box box-danger">
    <div class="box-header bg-navy" >
      <h2 class="box-title"><strong><i class="fa fa-questionmark fa-fw"></i> <?php
      echo get_setting('site_name'); ?> TEST AREA</strong> </h2><p>
    </div>
  <div class="box-body" >

    <div class="col-md-12 jumbotron" style="text-align:center;">
      <h2>WELCOME, <?php echo $_SESSION['user_session']->user_first_name." ".$_SESSION['user_session']->user_last_name?>!</h2>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#listSubjects">
      <i class="fa fa-list"></i> SELECT SUBJECT
      </button>

      <a href="?testRoom&action=viewResulthistory" type="button" class="btn btn-info btn-lg" >
      <i class="fa fa-eye"></i> RESULT HISTORY
      </a>
    </div>

    <!-- Subject Modal -->
    <div class="modal fade" id="listSubjects" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header bg-black">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <h4 class="modal-title" id="myModalLabel">SUBJECT LIST</h4>
            </div>
            <div class="modal-body">
              <table class="table table-striped table-bordered">
                <?php
                  $rs = mysqli_query( $connect, "SELECT * FROM academic_subjects ");
                  while($row=mysqli_fetch_array($rs)):
                ?>
                <tr>
                  <td>
                    <a href="?testRoom&action=getSubjectid&
                    subid=<?php echo $row['id']?>&subname=<?php echo $row['name']?>"
                    class="btn btn-info btn-block"><font size=3>
                    <?php echo $row['name']?></font></a>
                  </td>
                </tr>
                <?php
                endwhile;
                ?>
              </table>
            </div>
            <div class="modal-footer bg-black">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a href="?testRoom&action=option" type="button" class="btn btn-primary">TEST ROOM</a>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="box-footer bg-navy">
  </div>

  </div>
</div>
