<table <?php echo table_style() ?>>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desciption</th>
      <th></th>
      <th>Actions</th>
    </tr>
    <tbody>
      <?php
        foreach ($table_data as $key => $v ):
      ?>
      <tr>
        <td><?php echo $v['name'] ?></td>
        <td><?php echo $v['description'] ?></td>
        <td></td>
        <td>
          <?php if ( access_check("can_delete_academic_level")): ?>
            <a href="<?php echo APP_PATH . basename( __DIR__ ) . DS . "delete?token=" . $v['token'] ?>" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete <?php echo $v['name'] ?>')" > <i class="fa fa-trash"></i> Delete</a>
          <?php endif; ?>

          <?php if ( access_check( "can_edit_academic_level" ) ): ?>
            <a href="<?php echo APP_PATH . basename( __DIR__ ) . DS . "edit?token=" . $v['token'] ?>" class="btn btn-info">  <i class="fa fa-edit"></i> Edit</a>
          <?php endif; ?>

        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </thead>
</table>
