<?php
  $user_obj = new user;
  $users = $user_obj->get_system_users();
  $access_obj = new access;
?>

      <form method="post" action="#" class="vertical">

      <div class="form-group col-md-6">
        <label>Name</label>
        <input type="text" name="name" class="form-control" value="<?php echo $name ?>">
      </div>


      <div class="form-group col-md-6">
        <label>Phone Number</label>
        <input type="tel" name="phone_number" class="form-control" value="<?php echo $phone_number ?>">
      </div>




      <div class="form-group col-md-6">
        <label>Email Address</label>
        <input type="email" name="email_address" class="form-control" value="<?php echo $email_address ?>">
      </div>

      <div class="form-group col-md-6">
        <label>Website</label>
        <input type="url" name="website" class="form-control" value="<?php echo $website ?>">
      </div>


      <div class="form-group col-md-6">
        <label>Address</label>
        <textarea name="address" rows="3" class="form-control"><?php echo $address ?></textarea>
      </div>

      <div class="form-group col-md-6">
        <label>Map</label>
        <textarea name="map" rows="3" class="form-control"><?php echo $map ?></textarea>
      </div>

      <div class="form-group col-md-6">
        <label>Head Of Annex</label>
        <select  class="form-control select" data-live-search="true" name="hoa">
            <option></option>
            <?php
                foreach($users as $user):
            ?>
            <option  value="<?php echo $user['id'] ?>"><?php echo get_user_full_name( array( 'id' => $user['id'] ) )." | ".strtoupper($user['user_role']) ?></option>
          <?php endforeach?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label>Asst Head Of Annex</label>
        <select  class="form-control select" data-live-search="true" name="ahoa">
            <option></option>
            <?php
                foreach($users as $user):
            ?>array( '' =>
            <option  value="<?php echo $user['id'] ?>"><?php echo get_user_full_name( array( 'id' => $user['id'] ) )." | ".strtoupper($user['user_role']) ?></option>
          <?php endforeach?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label>Bursar</label>
        <select  class="form-control select" data-live-search="true" name="bursar">
            <option></option>
            <?php
                foreach($users as $user):
            ?>
            <option  value="<?php echo $user['id'] ?>"><?php echo get_user_full_name( array( 'id' => $user['id'] ) )." | ".strtoupper($user['user_role']) ?></option>
          <?php endforeach?>
        </select>
      </div>

      <div class="form-group col-md-6">
        <label>Receptionist</label>
        <select  class="form-control select" data-live-search="true" name="receptionist">
            <option></option>
            <?php
                foreach($users as $user):
            ?>
            <option  value="<?php echo $user['id'] ?>"><?php echo get_user_full_name( array( 'id' => $user['id'] ) )." | ".strtoupper($user['user_role']) ?></option>
          <?php endforeach?>
        </select>
      </div>

      <div class="form-group col-md-12">
          <button type="submit" name="<?php echo $button_name ?>" class="btn btn-primary pull-left"> <i class="fa fa-<?php echo $button_icon ?>"></i>  <?php echo $button_value ?></button>
          <button type="reset"  class="btn btn-danger pull-right"> <i class="fa fa-refresh"></i>  Reset</button>
      </div>

      </form>
