
    <?php get_header("Note Module Setting")?>
    <body>
        <!-- START PAGE CONTAINER -->
        <div class="page-container">
            
            <!-- START PAGE SIDEBAR -->
            <?php require TEMPLATES_PATH."elements/sidebar.phtml";?>
            
            <!-- PAGE CONTENT -->
            <div class="page-content">
                <?php require TEMPLATES_PATH."elements/header-bar.phtml";?>                                    
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li><a href="?page=notes">Notes</a></li>                    
                    <li class="active">Settings</li>
                </ul>
                <!-- END BREADCRUMB -->                
                
                <div class="page-title">                    
                    <h2><span class="fa fa-arrow-circle-o-left"></span> Lesson Note Module Setting</h2>
                </div>                   
                
                <!-- PAGE CONTENT WRAPPER -->
                <div class="page-content-wrap">                
                    <div class="row">
                        <div class="col-md-12">
                         <?php
                          $access_obj = new access;
                          echo $access_obj->current_user_capability()
                         ?>

                           
                        </div>
                    </div>
                
                </div>
                <!-- END PAGE CONTENT WRAPPER -->                
            </div>            
            <!-- END PAGE CONTENT -->
        </div>
        <!-- END PAGE CONTAINER -->
        <?php get_footer()?>

    






