<?php
  get_header("Modules Manager");
  $module_obj = new modules;
?>

<div class="panel panel-danger">
  <div class="panel-heading">
    <button type="button" class="btn btn-danger new pull-right" id="btn-new-module"> <i class="fa fa-plus"></i> New </button>
    <div class="panel-title">
      System Modules
    </div>
  </div>

  <div class="panel-body">
    <table class="table datatable" id="academic-subjects">
      <thead>
        <tr>
          <th>Name</th>
          <th>Destination</th>
          <th>Reg Date</th>
        </tr>

      </thead>
        <?php
          $modules = $module_obj->get_modules();
          foreach ($modules as $key => $v):
        ?>
        <tr>
          <td><?php echo $v['name'] ?></td>
          <th><?php echo $v['description'] ?></th>
          <th><?php echo $v['reg_date'] ?></th>
        </tr>
        <?php endforeach; ?>
      <tbody>

      </tbody>
    </table>

  </div>

  <div class="panel-footer">

  </div>

</div>


<script type="text/javascript">

  function modules(){
    this.update = function()
                  {
                    $(".edit").click(function(){
                      var name = $(this).attr("data-name");
                      var description = $(this).attr("data-descriptione");
                      var token = $(this).attr("data-token");
                      var modalTitle =  "<strong>" + "Editing " + name + "</strong>" ;
                      var template = '<form class="" id="edit-module" action="javascript://" method="post">'
                      + '<div class="form-group">'
                      + '<label for="">Subject Name</label>'
                      + '<input type="text" id="name" name="name" value="" class="form-control" required>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<label for="">Subject Token</label>'
                      + '<input type="text" id="token" name="token" value="" class="form-control" readonly>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<label for="">Subject Description</label>'
                      + '<textarea name="description" id="description" class="form-control" rows="2"></textarea>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<button type="submit" name="" id="modalSubmitButton" class="btn btn-success"><i class="fa fa-save"></i> Save </button>'
                      + '</div>'
                      + '</form>'
                      $("#modalTitle").html( modalTitle );
                      // alert( name + description + token );
                      $("#thisModal").modal("show");
                      $("#thisModalBody").html(template);
                      $("#name").val(name);
                      $("#description").val(description);
                      $("#token").val(token);
                      $("#edit-module").submit(function(){
                        var data = $(this).serialize();

                        $.ajax({
                          method : "POST",
                          url : "crud",
                          data: data + "&what_to_do=update",
                          cache : false,
                          beforeSend : function(){
                            notify.ajax_beforeSend();
                          },
                          complete: function(){

                          },
                          success: function(data){
                            notify.ajax_beforeComplete();
                            notify.noty(data);
                          }
                        })
                      })


                    });
                  };
    this.delete = function(){
      $(".delete").click(function(){
        var name = $(this).attr("data-name");
        var token = $(this).attr("data-token");
        return confirm("Are you you want to delete this subject ");
        var data = "token=" + token;
        $.ajax({
          method : "POST",
          url : "crud",
          data: data + "&what_to_do=delete",
          cache : false,
          beforeSend : function(){
            notify.ajax_beforeSend();
          },
          complete: function(){

          },
          success: function(data){
            notify.ajax_beforeComplete();
            notify.noty(data);
          }
        });

      })
    },
    this.create = function()
                  {
                    $(".new").click(function(){
                      // alert(location.href);
                      var modalTitle =  "<strong> NEW MODULE</strong>" ;
                      var template = '<form class="" id="new-module" action="javascript://" method="post">'
                      + '<div class="form-group">'
                      + '<label for="">Name</label>'
                      + '<input type="text" id="name" name="name" value="" class="form-control" required>'
                      + '</div>'

                      + '<div class="form-group">'
                      + '<label for="">Description</label>'
                      + '<textarea name="description" id="description" class="form-control" rows="2"></textarea>'
                      + '</div>'
                      + '<div class="form-group">'
                      + '<button type="submit" name="" id="modalSubmitButton" class="btn btn-success"><i class="fa fa-save"></i> Save </button>'
                      + '</div>'
                      + '</form>'
                      $("#modalTitle").html( modalTitle );
                      $("#thisModal").modal("show");
                      $("#thisModalBody").html(template);

                      $("#new-module").submit(function(){
                        var data = $(this).serialize();
                        // alert( data );
                        // return;

                        $.ajax({
                          method : "POST",
                          url : location.href + "/crud",
                          data: data + "&what_to_do=new&sp_show_error",
                          cache : false,
                          beforeSend : function(){
                            notify.ajax_beforeSend();
                            // alert(data);

                          },
                          complete: function(){

                          },
                          success: function(data){
                            form.emptyform("#new-module");
                            notify.ajax_beforeComplete();
                            notify.noty(data);
                            // alert(data);
                          }
                        })
                      })


                    });
                  };

  }
 var module = new modules;
 module.update();
 module.delete();
 module.create();
</script>

<!-- Modal content-->
<div class="modal  fade-in" id="thisModal" role="dialog">
  <div class="modal-dialog  modal-md">
    <div class="modal-content ">

      <div class="modal-header ">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title" id="modalTitle" ></h4>
      </div>

      <div class="modal-body" id="thisModalBody">
      </div>

      <div class="modal-footer ">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


<?php get_footer() ?>
