<div class="btn-group">
  <a href="<?php echo APP_PATH?>requisition/list" class="btn btn-info"><i class="fa fa-list"></i> History </a>
  <a href="javascript://" class="btn btn-primary" onclick="print()"><i class="fa fa-print"></i>  Print</a>
  <a href="?no-distraction" class="btn btn-warning" ><i class="fa fa-eye"></i>  Screen View</a>
</div>
<form method="post" action="#" class="vertical">

<div class="form-group col-md-4">
  <label>Annex</label>
  <input type="text" name="annex" class="form-control" value="">
</div>
<div class="form-group col-md-4">
  <label>Vendor</label>
  <input type="text" name="vendor" class="form-control" value="">
</div>

<div class="form-group col-md-4">
  <label>Vendor's  Location</label>
  <input type="text" name="vendor_location" class="form-control" value="">
</div>

<i class="fa fa-plus btn btn-danger new-item"></i>
<div class="form-group col-md-12 article-of-purchase">
  <div class="new-article-of-purchase">
    <div class="form-group col-md-6">
      <label>Item</label>
      <input type="text" name="item[]" class="form-control" value="" required>
    </div>
    <div class="form-group col-md-6">
      <label>Item Price</label>
      <input type="number" name="price[]" class="form-control" value="" required>
    </div>
  </div>
</div>

<div class="form-group col-md-6">
  <label>Department</label>
  <input type="text" name="department" class="form-control" value="">
</div>

<div class="form-group col-md-6">
  <label>Date Purchase</label>
  <input type="date" name="date" class="form-control" value="">
</div>

<div class="form-group col-md-12">
    <button type="submit" name="btn-new-requisition" class="btn btn-primary pull-left"> <i class="fa fa-plus"></i>  Save</button>
    <button type="reset"  class="btn btn-danger pull-right"> <i class="fa fa-refresh"></i>  Reset</button>
</div>


</form>


<script>
$(".new-item").click(function(){
  var item = '<div class="form-group col-md-6 "><label>Item</label><input type="text" name="item[]" class="form-control" value=""></div>';
  var price = '<div class="form-group col-md-6"><label>Item Price</label><input type="number" name="price[]" class="form-control" value=""></div>';
  $(".new-article-of-purchase").append(item + price);
});
</script>
