<div class="btn-group">
  <a href="<?php echo APP_PATH?>requisition/new" class="btn btn-info"><i class="fa fa-plus"></i> New </a>
  <a href="javascript://" class="btn btn-primary" onclick="print()"><i class="fa fa-print"></i>  Print</a>
  <a href="?no-distraction" class="btn btn-warning" ><i class="fa fa-eye"></i>  Screen View</a>
</div>
<table class="table table-striped table-bordered table-hover" id="datatable" cellspacing="0" width="100%" >
  <thead>
    <tr>
      <th>Status</th>
      <th>Annex</th>
      <th>Vendor</th>
      <th>Vendor's Location</th>
      <th>Item(s)</th>
      <th>N Price(s)</th>
      <th>Total Item(s)</th>
      <th>Total Price</th>
      <th>Date</th>
      <th>Staff</th>
      <th>Action</th>

    </tr>
  </thead>

  <tbody><?php
    $req_obj = new requisition;
    $results = $req_obj->full_data();
    if($results !== false)
    foreach($results as $result):
      $items =  unserialize($result['item']);
      $prices =  unserialize($result['price']);
  ?>
    <tr>
      <td>
        <?php
          if( $result['status'] =="" || $result['status'] ==" "):
            echo "<button class='btn btn-warning'>Pending</button>";
          elseif($result['status'] =="approved"):
            echo "<button class='btn btn-success'><i class='fa fa-check'></i> Approved</button>";
          elseif($result['status'] =="disapproved"):
            echo "<button class='btn btn-danger'><i class='fa fa-times'></i> Disapproved</button>";
          endif;
        ?>
      </td>
      <td><?php echo $result['annex'];  ?></td>
      <td><?php echo $result['vendor'];  ?></td>
      <td><?php echo $result['vendor_location'];  ?></td>
      <td >
        <ul>
        <?php
          foreach($items as $item):
            echo "<li>{$item}</li></br>";
          endforeach;
        ?>
        </ul>

      </td>
      <td >
        <ul>


        <?php
          foreach($prices as $price):
            echo "<li>{$price}</li></br>";
          endforeach;

        ?>
        </ul>
      </td>
        <td><?php echo count($items)  ?></td>
      <td><?php echo money_format('%i',array_sum($prices));  ?></td>
      <td><?php echo $result['date'];  ?></td>
      <td><?php echo get_user_full_name( array( 'id' => $result['user_id'] ) );  ?></td>
      <td>
        <?php
          if( $result['status'] =="" || $result['status'] ==" "):
            echo "<button class='btn btn-warning'>Pending</button>";
          elseif($result['status'] =="approved"):
            echo "<button class='btn btn-danger' title='If you click this, you will disapprove the request'><i class='fa fa-times'></i> Disapproved</button>";
          elseif($result['status'] =="disapproved"):
            echo "<button class='btn btn-success' onclick='' title='If you click this, you will approve the request'><i class='fa fa-check'></i> Approved</button>";
          endif;
        ?>
      </td>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>
