<?php
  get_header("Add Question to ( " . $_REQUEST['test'] . ")" );
  $test_obj = new test( $_REQUEST['test'] );
  $test = $test_obj->get_test( array('test_name' => $_REQUEST['test'] ) );



  // var_export($test);
  if( $test ):
    // var_export($test);
    $subject = $test['academic_subject'];
    $level = $test['academic_level'];
    $question_bank_obj = new question_bank;
    $parameters['academic_level'] = $level;
    $parameters['academic_subject'] = $subject;
    $questions = $question_bank_obj->get_questions( $parameters );
    if($questions):

?>
<div class="response_form_test">

</div>
    <?php else: ?>

      <?php if( ! isset($_GET['show_all'] ) ): ?>
      <div class="alert alert-danger">
        No question is associted with the Academic Subject & Academic Level of this test.
        Added new questions to the <strong>Question Bank</strong> with this test <strong>Academic Subject (<?php echo get_academic_subject($subject)['name'] ?>)</strong>  &  <strong>Academic Level (<?php echo get_academic_level($level)['name'] ?>)</strong>
        <a class="btn btn-info" href="?test=<?php echo addslashes( $_GET['test'] ) . "&token=" . addslashes( @$_GET['token']) ?>&show_all=1"> Show all</a>
      </div>
    <?php endif; ?>

    <?php endif; ?>

  <form class="test-questions" action="javascript://" method="post">
    <input type="hidden" name="url" id="url" value="<?php echo APP_PATH ?>">
    <input type="hidden" id="test" value="<?php echo $test['token'] ?>">
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h1 class="panel_title"></h1>
      <button type="button" data-code="<?php echo APP_PATH ?>" id="btn-new-test" class="btn btn-info"  name="button"> <i class="fa fa-plus"></i> Add Test</button>
    </div>

    <div class="panel-body">
      <table class="table table-striped table-bordered table-hover" id="datatable" cellspacing="0" width="100%" >
        <thead>
          <tr>
            <th></th>
            <th>Question</th>
            <th>Option1 </th>
            <th>Option2</th>
            <th>Option3</th>
            <th>Option4</th>
            <th>Real Answer</th>
            <th>Year</th>
            <th>Source</th>
          </tr>
        </thead>
        <tbody>
          <?php if (isset($_GET['show_all'])) {
            $questions = $question_bank_obj->get_questions( array() );
          } ?>
          <?php
            foreach ( $questions as $key => $v ):
          ?>
          <tr>
            <td> <input type="checkbox" class="add_question" app-url="<?php echo APP_PATH; ?>" data-code="<?php echo $test['token'] ?>" name="add_question[]" value="<?php echo $v['token'] ?>" <?php if( in_array( $v['id'] , $test_obj->get_tests_question_id($_REQUEST['test']) ) ): echo "checked" ; endif; ?>
 multiple> </td>
            <td><?php echo $v['question'] ?></td>
            <td><?php echo $v['option1'] ?></td>
            <td><?php echo $v['option2'] ?></td>
            <td><?php echo $v['option3'] ?></td>
            <td><?php echo $v['option4'] ?></td>
            <td><?php echo $v['answer'] ?></td>
            <td><?php echo $v['year'] ?></td>
            <td><?php echo get_question_source( $v['question_source'] )['name'] ; ?></td>
          </tr>
          <?php endforeach; ?>

        </tbody>
      </table>

    </div>

    <div class="panel-footer">
      <?php if( $questions ): ?>
      <button type="submit" class="btn btn-danger" name="btn-add-questions"> <i class="fa fa-plus fa-2x"></i> </button>
    <?php endif; ?>
    </div>

  </div>
</form>
<?php else: ?>
  <div class="alert alert-danger">
    No test is associated with this link.
    <button type="button" data-code="<?php echo APP_PATH ?>" id="btn-new-test" class="btn btn-info"  name="button"> <i class="fa fa-plus"></i> Add Test</button>

  </div>
<?php endif; ?>

<script type="text/javascript">
  $(".test-questions").submit(function(){
    data = $(this).serialize();
    url = $("#url").val();
    test = $("#test").val();
    // alert(url);
    $.ajax({
      method : "POST",
      url : url + "test/crud",
      data : data + "&what_to_do=add_question_to_test&test=" + test,
      cache : false,
      beforeSend : function(){
        notify.ajax_beforeSend();
      },
      complete: function(){
        notify.ajax_beforeComplete();
      },
      success: function(data){
        form.emptyform(".form-new-test");
        notify.ajax_beforeComplete();
        notify.noty(data);
        alert(data);
        $(".response_form_test").html(data);
        // alert(data);
      }
    })
  });
  $("#btn-new-test").click(function(){
    data = $(this).attr("data-code");
    location.replace( data + "test")
  })
</script>
<?php get_footer(); ?>
