<?php
  $test_obj = new test();
  // if( access_check($test_obj::CAN_CREATE) ){
  //   exit;
  // }
  get_header("Test Creator");
?>

<?php
  if( access_check( $test_obj::CAN_CREATE ) ):

    if( isset( $_POST['btn-new-test'] ) )
    {
      $test_obj->add_test();
    }
?>
  <form class="" action="#" method="post">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <div class="panel_title">
          TEST CREATOR
        </div>

      </div>

      <div class="panel-body">
        <div class="col-md-12" id="response_form_test">

        </div>
        <div class="form-group col-md-6">
          <label for="test_name">Test Name</label> <?php echo educate( "Test name" , "Specify the name of the test. Let the name specify the purpose of the test") ?>
          <input type="text" class="form-control" name="test_name" id="test_name" placeholder="Test name">
        </div>

        <div class="form-group col-md-6">
          <label for="duration">Test Duration</label> <?php echo educate( "Test Duration" , "Specify the duration of this test.  If no duration is specify , then the time is nulimited. ") ?>
          <input type="number" class="form-control"  name="duration" id="duration" placeholder="10">
        </div>

        <div class="form-group col-md-6">
          <label for="academic_subject">Academic Subject</label> <?php echo educate(" Subject" , "Select which Academic Subject has the test, else leave empty for general") ?>
          <select class="form-control select" data-live-search="true" name="academic_subject">
            <option></option>
            <?php
              $academic_subject_obj = new academic_subjects;
              $subjects = $academic_subject_obj->get_academic_subjects();
              foreach ($subjects as $key => $v) :
            ?>
            <option value="<?php echo $v['id'] ?>"><?php echo $v['name'] ?></option>
            <?php endforeach; ?>
          </select>
        </div>

        <div class="form-group col-md-6">
          <label for="academic_class">Academic Level</label> <?php echo educate(" Class" , "Select which Academic Class has the test, else leave empty for general") ?>
          <select class="form-control select" data-live-search="true" name="academic_level">
            <option></option>
            <?php
              $academic_level_obj = new academic_levels;
              $levels = $academic_level_obj->get_full_data();
              foreach ($levels as $key => $v) :
            ?>
            <option value="<?php echo $v['id'] ?>"><?php echo $v['name'] ?></option>
            <?php endforeach; ?>
          </select>
        </div>

      </div>

      <div class="panel-footer">
        <button type="submit" name="btn-new-test" class="btn btn-info "> <i class="fa fa-save"></i> Save </button>

      </div>

    </div>
  </form>
<?php endif; ?>




<script type="text/javascript">



  $(".form-new-test").submit(function(){
    var data = $(this).serialize();
    // alert(location.href);
    $.ajax({
      method : "POST",
      url : "../crud",
      data : data + "&what_to_do=new",
      cache : false,
      beforeSend : function(){
        notify.ajax_beforeSend();
      },
      complete: function(){
        notify.ajax_beforeComplete();
      },
      success: function(data){
        form.emptyform(".form-new-test");
        notify.ajax_beforeComplete();
        notify.noty(data);
        $("#response_form_test").html(data);
        // alert(data);
      }
    })
  })

</script>




<?php get_footer() ?>
