<style>
.style1 {
	color: #FFFFFF;
	font-weight: bold;
}
.style2 {
	color: #990000;
	font-weight: bold;
}
.style4 {
	color: #000000;
	font-weight: bold;
}
.style5 {color: #990033}
.style6 {color: #ECE9D8}
.style7 {
	color: #993300;
	font-weight: bold;
}
.style8 {
	color: #6633CC;
	font-weight: bold;
}

.errors {

	color: #FF0000;
	font-weight: bold;
}
.tot {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 16px;
	color: #000000;
}
.tot {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color: #000000;

}
.tans {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color:#00CC66 ;
}
.fans {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 18px;
	font-weight: bold;
	color:#FF0000 ;
}
</style>

<?php
@extract($_POST);
$test_name = $_GET['test'];
// $subid = $_GET['subid'];
@extract($_SESSION);
$sql_obj = new sql_datacrud;

$db_obj = new Database;
$connect = $db_obj->dbConnection();
/*$rs=mysql_query("select * from skulPRO_question where test_id=$test_name",$cn) or die(mysql_error());
if($_SESSION['qn']>mysql_num_rows($rs))
{
unset($_SESSION['qn']);
exit;
}*/
?>

<div class="col-md-12 jumbotron" style="text-align:center;">
	<?php
	/*$rs=mysql_query("select * from skulPRO_question where test_id=$test_name",$cn) or die(mysql_error());
	if($_SESSION['qn']>mysql_num_rows($rs))
	{
	unset($_SESSION['qn']);
	exit;
	}*/
	if(isset($subid) && isset($test_name))
	{
	$_SESSION[sid]=$subid;
	$_SESSION[test_name]=$test_name;
	}
	/*if(!isset($_SESSION[sid]) || !isset($_SESSION[test_name]))
	{
		header("location: index.php");
	}*/
	?>
	<?php
	@extract($_POST);
	$test_name = $_GET['test'];
	// $subid = $_GET['subid'];
	@extract($_SESSION);

	$query="SELECT * FROM skulPRO_question";

	$rs = mysqli_query($connect, "SELECT * FROM skulpro_test_questions WHERE test_name='{$test_name}' ") or die(mysqli_error());
	if(!isset($_SESSION['qn']))
	{
		$_SESSION['qn']=0;
		mysqli_query($connect, "DELETE FROM skulpro_test_answers WHERE sess_id='" . session_id() ."'") or die(mysqli_error());
		$_SESSION['trueans']=0;

	}
	else
	{
			if( isset($_POST['next'])  && isset($ans))
			{
				mysqli_data_seek( $rs ,$_SESSION['qn'] );
				$row = mysqli_fetch_row( $rs );
				$form_data = array(
					"sess_id" => session_id(),
					"test_name" => $test_name,
					"que_des" => $row[2],
					"ans1" => $row[3],
					"ans2" => $row[4],
					"ans3" => $row[5],
					"ans4" => $row[6],
					"true_ans" => $row[7],
					"your_ans" => $ans,
				);
				$sql_obj->insert_data( "skulpro_test_answers" , $form_data );
				// mysqli_query($connect, "insert into skulpro_test_answers(sess_id, test_id, que_des, ans1,ans2,ans3,ans4,true_ans,your_ans) values ('".session_id()."', $test_name,'$row[2]','$row[3]','$row[4]','$row[5]', '$row[6]','$row[7]','$ans')") or die(mysql_error());
				if($ans==$row[7])
				{
					$_SESSION['trueans']=$_SESSION['trueans']+1;
				}
				$_SESSION['qn'] = $_SESSION['qn']+1;
			}
			elseif(isset($_POST['get_result']) && isset($ans))
			{
				mysqli_data_seek($rs,$_SESSION['qn']);
				$row= mysqli_fetch_row($rs);
				$form_data = array(
					"sess_id" => session_id(),
					"test_name" => $test_name,
					"que_des" => $row[2],
					"ans1" => $row[3],
					"ans2" => $row[4],
					"ans3" => $row[5],
					"ans4" => $row[6],
					"true_ans" => $row[7],
					"your_ans" => $ans,
				);
				$sql_obj->insert_data( "skulpro_test_answers" , $form_data );

				// mysqli_query($connect, "INSERT INTO skulpro_test_answers(sess_id, test_id,
				// que_des, ans1,ans2,ans3,ans4,true_ans,your_ans)
				// values ('".session_id()."', $test_name,'$row[2]','$row[3]','$row[4]','$row[5]',
				// '$row[6]','$row[7]','$ans')") or die(mysqli_error());
				if($ans==$row[7])
				{
							$_SESSION['trueans']=$_SESSION['trueans']+1;
				}
				echo "<h1 class=head1> Result</h1>";
				$_SESSION['qn']=$_SESSION['qn']+1;
				echo "<Table align=center><tr class=tot><td>Total Question<td> {$_SESSION['qn']}";
				echo "<tr class=tans><td>True Answer<td>".$_SESSION['trueans'];
				$w=$_SESSION['qn']-$_SESSION['trueans'];
				echo "<tr class=fans><td>Wrong Answer<td> ". $w;
				echo "</table>";
				$user = get_user( array('token' => $_SESSION['user_session']->token ) )['id'];
				$form_data = array(
					"login" => session_id(),
					"test_name" => $test_name,
					"test_date" => date("d-m-Y h:i:s"),
					"score" => $_SESSION['trueans'],
				);
				$sql_obj->insert_data( "skulpro_result" , $form_data );
				echo '<h1 align="center"><a href="?testRoom&action=viewResult"> Review Question</a> </h1>';
				unset($_SESSION['qn']);
				unset($_SESSION[sid]);
				unset($_SESSION['test_name']);
				unset($_SESSION['trueans']);
				exit;
			}
	}
	$rs = mysqli_query($connect, "SELECT * FROM skulpro_test_questions WHERE test_name='{$test_name}'") or die(mysqli_error());
	if($_SESSION['qn']>mysqli_num_rows($rs)-1)
	{
	unset($_SESSION['qn']);
	echo '<h1>Some Error  Occured. Please start again</h1>';
	//session_destroy();
	echo 'Please <a href="?testRoom&action=listSubjects"
	class="btn btn-info"> <i class="fa fa-clock-o"></i> Start Again</a>';
	exit;
	}
	mysqli_data_seek($rs,$_SESSION['qn']);
	$row= mysqli_fetch_row($rs);
	$rowCount = mysqli_num_rows($rs);
	?>
	<?php
	if($rowCount > 0):
		echo "<form class='form-question' method='post' action='#'>";
		echo "<table width=100%> <tr> <td width=30>&nbsp;<td> <table border=0>";
		$n=$_SESSION['qn']+1;
		echo "<tr><td align=left><span class=style2><h2>Que ".  $n .": $row[2]</h2></style>";
		echo "<tr><td align=left
		class=style8><h4>A: &nbsp; &nbsp;  <input type=radio name=ans value=1> $row[3]</h4>";
		echo "<tr><td align=left
		class=style8><h4>B: &nbsp; &nbsp;  <input type=radio name=ans value=2> $row[4]</h4>";
		echo "<tr><td align=left
		class=style8><h4>C: &nbsp; &nbsp;  <input type=radio name=ans value=3> $row[5]</h4>";
		echo "<tr><td align=left
		class=style8><h4>D: &nbsp; &nbsp;  <input type=radio name=ans value=4> $row[6]</h4>";
	endif;
	?>
	<?php
	if($_SESSION['qn'] < mysqli_num_rows( $rs ) - 1 ):
		echo '<tr><td><input type="submit" class="btn btn-success" name="next" value="Next Question"></form>';
	else:
		echo '<tr><td><input type="submit" class="btn btn-info" name="get_result" value="Get Result"></form>';
		echo "</table></table>";
	endif;
	?>

</div>
