<?php
  $rs = mysqli_query( $connect, "SELECT * FROM skulpro_test_questions WHERE test_name='{$test_name}' " ) or die(mysqli_error());

  if( $_SESSION['qn'] > mysqli_num_rows( $rs ) - 1 ):
    unset($_SESSION['qn']);
    echo "<h1 class='text-danger'>Some Error  Occured. Please start again</h1>";
    // session_destroy();
    $url = APP_PATH . "test/";
    echo " <a href='{$url}' class='btn btn-info'> <i class='fa fa-clock'></i>Please Start Again</a>";
    exit;
  endif;

?>
